### ISSUE TITLE
Cannot build on macOS: fatal error: 'cassert' file not found

### ISSUE THREAD

**Issue by Lorp** [harfbuzz/harfbuzzjs#34]
I’m getting this error, trying to build on macOS 10.14.6 :

```
/Users/lorp/Sites/harfbuzzjs % ./build.sh
In file included from harfbuzz/src/harfbuzz.cc:1:
In file included from harfbuzz/src/hb-aat-layout.cc:28:
harfbuzz/src/hb.hh:179:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
```

My clang and lld seem to be installed ok.

Any ideas?

**Comment by behdad** [comment]
Ugh. That's because of this change:

  https://github.com/harfbuzz/harfbuzz/commit/7cb22ba7ebf6ef053790a3201cb7014bacd51e46

Can you change back that `cassert` to `assert.h` and see which other headers fail there?

**Comment by Lorp** [comment]
Now this happens…
```
In file included from harfbuzz/src/harfbuzz.cc:1:
In file included from harfbuzz/src/hb-aat-layout.cc:28:
harfbuzz/src/hb.hh:180:10: fatal error: 'cfloat' file not found
#include <cfloat>
         ^~~~~~~~
```

**Comment by behdad** [comment]
Okay I let someone else to chime in. Looks like badly setup toolchain to me. Not sure what harfbuzzjs calls...

**Comment by behdad** [comment]
Do you happen to have a newer MacOS version to try?

**Comment by behdad** [comment]
I get a ton of other errors when I try to compile the way you are...

**Comment by Lorp** [comment]
I don’t have a newer macOS version right now.

**Comment by behdad** [comment]
Does it work if you revert that HarfBuzz commit?

**Comment by behdad** [comment]
Something's definitely wrong with how harfbuzzjs invokes the compiler. I can't get it work here though.

**Comment by Lorp** [comment]
With the previous `dbcf2f41` I get:

```
/Users/lorp/Sites/harfbuzzjs % ./build.sh
In file included from harfbuzz/src/harfbuzz.cc:1:
In file included from harfbuzz/src/hb-aat-layout.cc:35:
In file included from harfbuzz/src/hb-aat-layout-kerx-table.hh:31:
In file included from harfbuzz/src/hb-kern.hh:32:
In file included from harfbuzz/src/hb-ot-layout-gpos-table.hh:32:
harfbuzz/src/hb-ot-layout-gsubgpos.hh:3437:15: error: use of undeclared identifier 'alternate_feature_indices'
          && !alternate_feature_indices.has (i))
              ^
1 error generated.
```

**Comment by behdad** [comment]
Did running this "./build.sh" ever worked for you?

Maybe @ebraminio can respond.

**Comment by Lorp** [comment]
No, this is the first time. I am intending to compile with variations on.

**Comment by ebraminio** [comment]
Headers issue is resolved however there are apparently some other issue on the upstream side,

```
$ gcc src/harfbuzz.cc -DHB_TINY
In file included from src/hb-ot-layout-gpos-table.hh:32,
                 from src/hb-kern.hh:32,
                 from src/hb-aat-layout-kerx-table.hh:31,
                 from src/hb-aat-layout.cc:35,
                 from src/harfbuzz.cc:1:
src/hb-ot-layout-gsubgpos.hh: In member function ‘void OT::GSUBGPOS::prune_features(const hb_map_t*, hb_set_t*) const’:
src/hb-ot-layout-gsubgpos.hh:3437:15: error: ‘alternate_feature_indices’ was not declared in this scope
 3437 |           && !alternate_feature_indices.has (i))
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ebraminio** [comment]
Headers issue is resolved however there are apparently other issues upstream side,

```
$ gcc src/harfbuzz.cc -DHB_TINY
In file included from src/hb-ot-layout-gpos-table.hh:32,
                 from src/hb-kern.hh:32,
                 from src/hb-aat-layout-kerx-table.hh:31,
                 from src/hb-aat-layout.cc:35,
                 from src/harfbuzz.cc:1:
src/hb-ot-layout-gsubgpos.hh: In member function ‘void OT::GSUBGPOS::prune_features(const hb_map_t*, hb_set_t*) const’:
src/hb-ot-layout-gsubgpos.hh:3437:15: error: ‘alternate_feature_indices’ was not declared in this scope
 3437 |           && !alternate_feature_indices.has (i))
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Apparently ArchLinux CI which also was testing HB_TINY and flake8 testing https://github.com/harfbuzz/harfbuzz/commit/094406b is disabled.

**Comment by behdad** [comment]
Ah... it didn't occur to me that the wasm toolchain doesn't come with any standard headers.  Thanks Ebrahim. I'll fix the other issue.

**Comment by ebraminio** [comment]
Am getting these also on a macOS device on harfbuzz source itself,

```
$ /usr/bin/clang src/harfbuzz.cc -std=c++11
In file included from src/harfbuzz.cc:1:
In file included from src/hb-aat-layout.cc:35:
In file included from src/hb-aat-layout-kerx-table.hh:31:
In file included from src/hb-kern.hh:32:
In file included from src/hb-ot-layout-gpos-table.hh:32:
src/hb-ot-layout-gsubgpos.hh:29:2: error: unterminated conditional directive
#ifndef HB_OT_LAYOUT_GSUBGPOS_HH
 ^
In file included from src/harfbuzz.cc:16:
In file included from src/hb-ot-face.cc:42:
In file included from src/hb-ot-layout-gsub-table.hh:32:
src/hb-ot-layout-gsubgpos.hh:29:2: error: unterminated conditional directive
#ifndef HB_OT_LAYOUT_GSUBGPOS_HH
 ^
2 errors generated.
```

```
$ /usr/bin/clang src/harfbuzz.cc -std=c++11 -DHB_TINY 
In file included from src/harfbuzz.cc:1:
In file included from src/hb-aat-layout.cc:35:
In file included from src/hb-aat-layout-kerx-table.hh:31:
In file included from src/hb-kern.hh:32:
In file included from src/hb-ot-layout-gpos-table.hh:32:
src/hb-ot-layout-gsubgpos.hh:29:2: error: unterminated conditional directive
#ifndef HB_OT_LAYOUT_GSUBGPOS_HH
 ^
In file included from src/harfbuzz.cc:16:
In file included from src/hb-ot-face.cc:42:
In file included from src/hb-ot-layout-gsub-table.hh:32:
src/hb-ot-layout-gsubgpos.hh:29:2: error: unterminated conditional directive
#ifndef HB_OT_LAYOUT_GSUBGPOS_HH
 ^
src/harfbuzz.cc:55:26: error: expected '}'
#include "hb-coretext.cc"
                         ^
src/hb-ot-layout-gsubgpos.hh:3292:1: note: to match this '{'
{
^
src/hb-ot-layout-gsubgpos.hh:3293:35: error: use of undeclared identifier 'version'
  bool has_data () const { return version.to_int (); }
                                  ^
src/hb-ot-layout-gsubgpos.hh:3295:18: error: use of undeclared identifier 'scriptList'
  { return (this+scriptList).len; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3297:18: error: use of undeclared identifier 'scriptList'
  { return (this+scriptList).get_tag (i); }
                 ^
src/hb-ot-layout-gsubgpos.hh:3301:18: error: use of undeclared identifier 'scriptList'
  { return (this+scriptList).get_tags (start_offset, script_count, script_tags); }
                 ^
src/hb-ot-layout-gsubgpos.hh:3303:18: error: use of undeclared identifier 'scriptList'
  { return (this+scriptList)[i]; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3305:18: error: use of undeclared identifier 'scriptList'
  { return (this+scriptList).find_index (tag, index); }
                 ^
src/hb-ot-layout-gsubgpos.hh:3308:18: error: use of undeclared identifier 'featureList'
  { return (this+featureList).len; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3310:62: error: use of undeclared identifier 'featureList'
  { return i == Index::NOT_FOUND_INDEX ? HB_TAG_NONE : (this+featureList).get_tag (i); }
                                                             ^
src/hb-ot-layout-gsubgpos.hh:3314:18: error: use of undeclared identifier 'featureList'
  { return (this+featureList).get_tags (start_offset, feature_count, feature_tags); }
                 ^
src/hb-ot-layout-gsubgpos.hh:3316:18: error: use of undeclared identifier 'featureList'
  { return (this+featureList)[i]; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3318:18: error: use of undeclared identifier 'featureList'
  { return (this+featureList).find_index (tag, index); }
                 ^
src/hb-ot-layout-gsubgpos.hh:3321:18: error: use of undeclared identifier 'lookupList'
  { return (this+lookupList).len; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3323:18: error: use of undeclared identifier 'lookupList'
  { return (this+lookupList)[i]; }
                 ^
src/hb-ot-layout-gsubgpos.hh:3332:13: error: use of undeclared identifier 'version'
    return (version.to_int () >= 0x00010001u ? this+featureVars : Null (FeatureVariations))
            ^
src/hb-ot-layout-gsubgpos.hh:3332:53: error: use of undeclared identifier 'featureVars'
    return (version.to_int () >= 0x00010001u ? this+featureVars : Null (FeatureVariations))
                                                    ^
src/hb-ot-layout-gsubgpos.hh:3383:53: error: no member named 'lookupList' in 'OT::GSUBGPOS'
    reinterpret_cast<OffsetTo<TLookupList> &> (out->lookupList)
                                               ~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by ebraminio** [comment]
Ignore my now deleted comment, this works now as expected, thanks!

**Comment by ebraminio** [comment]
@Lorp, just note on macOS you need to put brew installed clang on PATH instead toolchain brought one as the latter isn't updated enough unfortunately. In order to enable variation you'll need to apply but that's just the start as you'll need to wire up the variation APIs to .wasm (simply adding them to build.sh API listing part) and the .js/.ts wrapper,

```
diff --git a/config-override.h b/config-override.h
index 4366421..a5062ad 100644
--- a/config-override.h
+++ b/config-override.h
@@ -4,3 +4,4 @@
 #undef HB_NO_DRAW
 #undef HB_NO_BUFFER_MESSAGE
 #undef HB_NO_BUFFER_SERIALIZE
+#undef HB_NO_VAR
```

**Comment by Lorp** [comment]
Hey @ebraminio, thanks for the commits. It now builds and runs well, and also builds & runs when I edit `config-override.h` to add `#undef HB_NO_VAR` and export 3 variations functions in build.sh:

```
-Wl,--export=hb_ot_var_get_axis_count \
-Wl,--export=hb_ot_var_get_axis_infos \
-Wl,--export=hb_font_set_variations \
```

Then I added a `getAxisCount()` method in `createFace()` (in hbjs.js), which works perfectly :)

```
getAxisCount: function () {
  return exports.hb_ot_var_get_axis_count(ptr);
},
```

But I cannot seem to pass non-integer parameters, so I have not got `hb_ot_var_get_axis_infos()` or `hb_font_set_variations()` working. Maybe I have to pack the structures they need into blobs.

**Comment by Lorp** [comment]
My attempts:

```
// hbjs.js [in createFace()]
getAxisInfos: function (start_offset, axes_count_ptr, axes_array) {
  return exports.hb_ot_var_get_axis_infos(ptr, start_offset, axes_count_ptr, axes_array);
},

// hbjs.js [in createFont()]
setVariations: function (variations, variations_length) {
  exports.hb_font_set_variations(ptr, variations, variations_length);
},

// harfbuzzjs.html
let axisInfos = [];
let numAxesPtr = [numAxes]; // numAxes == 2
face.getAxisInfos(0, numAxesPtr, axisInfos);
let variations = [{tag:"wght", value: 800.0}, {tag:"wdth", value: 666.7}];
font.setVariations(variations, 2);
```

**Comment by ebraminio** [comment]
oh, wasm machine doesn't understand complex js structures, am trying to make it work for you :)

**Comment by ebraminio** [comment]
@Lorp: https://github.com/harfbuzz/harfbuzzjs/commit/cc798e577bf4fb8aaf6c4d2039ed7398203b44ce here you go :)

**Comment by Lorp** [comment]
That works perfectly! Thanks very much!

`face.getAxisInfos()` from `Recursive-VariableFont_CASL,CRSV,MONO,slnt,wght.ttf`:

```
{MONO: {min: 0, default: 0, max: 1}, CASL: {min: 0, default: 0, max: 1}, wght: {min: 300, default: 300, max: 1000}, slnt: {min: -15, default: 0, max: 0}, CRSV: {min: 0, default: 0.5, max: 1}}
```

![Recursive-wght-300-CASL-0](https://user-images.githubusercontent.com/587440/110057047-c3784d00-7d57-11eb-9f6c-a3ddd99b3996.png)
![Recursive-wght-1000-CASL-1](https://user-images.githubusercontent.com/587440/110057050-c5daa700-7d57-11eb-8ea9-5fa19b85c427.png)

**Comment by Lorp** [comment]
Is it possible to apply features?

From hbjs.example.js:
```
hb.shape(font, buffer); // features are not supported yet
```

**Comment by ebraminio** [comment]
> Is it possible to apply features?

Apparently we only have implemented it with https://github.com/harfbuzz/harfbuzzjs/blob/cc798e5/hbjs.js#L337 and not with the main https://github.com/harfbuzz/harfbuzzjs/blob/cc798e5/hbjs.js#L315 guess you can use shapeWithTrace and get a GSUB/GPOS applying steps trace also for free :)

**Comment by Lorp** [comment]
Success! It was failing when I constructed `features` as an object, but then I realized it must be a string. CSS syntax with on and off, single or double quotes, and comma separation works perfectly :)

```
let features = "'kern' off, 'frac' on";
hb.shapeWithTrace(font, buffer, features);
let result = buffer.json(font);
```
